jvm_app(
								name='main',
								basename = 'hello-pants',
								dependencies = [
								':main-bin'
								],
			 )

jvm_binary(
								name = 'main-bin',
								source = 'griffio/Main.java',
								main = 'griffio.Main',
								basename = 'hello-pants',
					)
